title: Brzermr's blog
description: "Share And Grow"
author:
  name: "Brzermr"
  email: "zhengma0211@gmail.com"
  url: "https://www.brzermr.xyz"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 1
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Brzermr"
year : "2021"
search: "search"
google_analytics: UA-189304741-1

gitalk:
clientID: 94b578e9990672bad7f9
clientSecret: ce0531c2d3548aaec28cd88e252a188257cd305c
repo: https://github.com/brzermr/brzermr.github.io.git
owner: brzermr
